### ISSUE TITLE
A bit of explaination for the demo

### ISSUE THREAD

**Issue by thhck** [ULB-Darmstadt/shacl-form#1]
Hello !

I'm runing the demo and I understand correctly the right side textarea is the template of the form, the bottom green/red text is the restult of the form, the demo html form is on the far right,
 but have struggle understanding the right side "Data" text-area , is it just an example of form result ? then why does it differ so much from the bottom result ?
 
 Would it be possible to have a small README in the demo folder ?

**Comment by s-tittel** [comment]
Thanks for reporting. A more in-depth documentation is in the works.

The form generator generally is intended to support creating data from scratch or edit existing data. The "data" textarea is supposed to provide sample data. So if you choose "Shape 1", you can afterwards (re)-select "Data 1" to provide some input data to the form.

**Comment by s-tittel** [comment]
The demo has improved and I think it explains the concepts much better now. Closing this, please reopen if there are still issues.
