### ISSUE TITLE
QUESTION: Rendered form control as "output"

### ISSUE THREAD

**Issue by claudius108** [ULB-Darmstadt/shacl-form#14]
Hi!

Before everything, I have to say that this component is absolutely magnificent!

I looked at the datatypes, and I have not seen a rendered "output" form control, which I need for a default value that has not to be modified by the user. 

Would you recommend me a plugin for this, or there is something else I missed so far?

Thank you!
Claudius

**Comment by s-tittel** [comment]
Hi and thanks!

You can use [sh:hasValue](https://www.w3.org/TR/shacl/#HasValueConstraintComponent) for that. Since v1.4.4, &lt;shacl-form&gt; renders a disabled (non-editable) input field in this case. For example:
```
      @prefix sh: <http://www.w3.org/ns/shacl#> .
      @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
      @prefix ex: <http://example.org#> .

      ex:ExampleShape
        a sh:NodeShape, rdfs:Class ;
        sh:property [
          sh:name 'my value' ;
          sh:hasValue 'non editable default value' ;
          sh:path ex:exampleValue ;
        ] .
```

**Comment by claudius108** [comment]
Thanks!
