### ISSUE TITLE
suggestion: showing URIs

### ISSUE THREAD

**Issue by renevoorburg** [ULB-Darmstadt/shacl-form#21]
When an RDF that is loaded into a form contains multiple references to an entity that is part of the RDF, the first occurrence of such a reference is used to display the data that is referred to in (a part of) the form. The next references are shown as a URIs only.

Basically I think this is a good approach, but there are downsides to the current implementation:

This is the only situation where URIs are shown. The URI shown doesn’t help the user to see which entity it refers to. In this situation it would be helpful if these (or all?) URIs were displayed in the form. For some use cases showing URIs would not be desirable, so ideally there would be a config setting for this.

It would also be helpful if clicking the URI would focus the relevant data in the form (anchor link).

**Comment by s-tittel** [comment]
v1.5.2 now has an attribute `show-node-ids` to enable displaying the node ids in the form. Also, think now scrolls the referenced node into view.

**Comment by renevoorburg** [comment]
Very nice!
One minor thing: I had to use attribute data-show-node-ids in stead of show-node-ids, to get it working.

**Comment by s-tittel** [comment]
ah - yes of course. I have updated the README file.

**Comment by renevoorburg** [comment]
Thanks!
