### ISSUE TITLE
Recommended use of multiple SKOS Concept Schemes (leading to sh:class skos:Concept)

### ISSUE THREAD

**Issue by Certiman** [ULB-Darmstadt/shacl-form#23]
### Context

We're extensively testing the library in a situation where several properties are modeled as below, as the range of `iss_dev:foo` is a SKOS Concept, of which the SKOS Scheme imported using `owl:imports`:

```
sh:property   [ 
    sh:description      "Foo" ;
    sh:minCount  1 ;
    sh:maxCount  1 ;
    sh:name "foo" ;
    sh:path      iss_dev:foo ;
    sh:class     skos:Concept ; # <<< Concepts
] ;
```

### Issue

We have several such concept schemes to import for several properties in the same Class, and as the `sh:class` is always `skos:Concept`, the select-element's option values are filled with *all* of them. Moreover, the different NodeShapes in the form defining shapefile where this `sh:class` is used all pull in the full set of Concepts in the select-element's option values. In essence, all the select elements are (evidently) sharing all the collected option values as there is no discriminatory mechanism to refine.

### Question

If we wish to avoid adding another rdf:type to the SKOS Concepts themselves (sh:class then allowing `skos:Concept , iss_dev:SkosClassBar`, how is this use case normally tackled? Thx.

**Comment by Certiman** [comment]
A potential solution could be to regroup the instances of 'skos:Concept' by their 'skos:inScheme'.

**Comment by s-tittel** [comment]
Thanks for reporting! Would it help if the imported vocabularies were scoped to the subgraph where the `owl:imports` statement is defined? For example:
```
sh:property   [ 
    owl:imports <http://example.org/taxonomy-1> ;
    sh:description      "Foo" ;
    sh:name "foo" ;
    sh:path      iss_dev:foo ;
    sh:class     skos:Concept ; # <<< Concepts of Taxonomy 1
] ;
sh:property   [ 
    owl:imports <http://example.org/taxonomy-2> ;
    sh:description      "Bar" ;
    sh:name "bar" ;
    sh:path      iss_dev:bar ;
    sh:class     skos:Concept ; # <<< Concepts  of Taxonomy 2
] ;
```

**Comment by Certiman** [comment]
Thanks for your reply and apologies for the delay due to holidays (and working on another project during). We updated the shapes file as above, but all Concepts from all locally imported schemes still get combined in each of the dropdown's `<option value="">`. Each of the `<select id="` is different.

**Comment by s-tittel** [comment]
Sorry for being imprecise and the delay (was on holiday too). At the time this wasn't implemented, I just wanted to check if the proposed solution would work for you.

Please check out version 1.6.0, it should work now.

**Comment by s-tittel** [comment]
Closing because I think it works. Please reopen if you see any issues.

**Comment by Certiman** [comment]
@s-tittel , thanks and apologies for the delays: I can confirm it now works as intended, using 1.6.3. Is it possible the jsdelivr.net repo is still an older version, I had to explicitly import 1.6.3.
Issue can remain closed.

**Comment by s-tittel** [comment]
@Certiman , thanks for confirming. Happy that it works now.

As far as I understand the [caching behavior of jsdelivr](https://github.com/jsdelivr/jsdelivr#caching), it can take up to 7 days to update the latest version. Maybe [unpk](https://unpkg.com/) is faster (?)

Personally, I use `shacl-form` with `npm install`, so no CDN involved.
