### ISSUE TITLE
Fragile to order of shapes

### ISSUE THREAD

**Issue by mgskjaeveland** [ULB-Darmstadt/shacl-form#25]
I noticed that the generated form changes if the order of the input shapes is changed. For instance, if the `example:Person` shape in your example (https://ulb-darmstadt.github.io/shacl-form/#example) is moved as the first node shape in the input, then the generated form ends up only supporting creating a single Person. 

Perhaps you should infer what the topmost shape(s) is/are and/or allow the topmost shapes to be specified? (Perhaps you already support this and I have missed it.)

**Comment by s-tittel** [comment]
Hi, correct, `shacl-form` does not try to infer a best matching shape. There a two ways to specify the root shape:

- as attribute `data-shape-subject` on the HTML element as [documted here](https://github.com/ULB-Darmstadt/shacl-form?tab=readme-ov-file#element-attributes)
- if you bind a data graph and it contains one of these triples:
  - `<subject>` `<http://purl.org/dc/terms/conformsTo>` `<rootShapeId>`
  - `<subject>` `<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>` `<rootShapeId>`
  then the referenced rootShapeId will be used

Closing, please reopen if you are still missing anything.
