### ISSUE TITLE
<shacl-form> Component doesn't auto populate data-values with RDF Data in certain formats

### ISSUE THREAD

**Issue by dmap1514** [ULB-Darmstadt/shacl-form#27]
When trying to autopopulate data-values for the <shacl-form> editor, I noticed that data-values are not automatically entered if the data-shapes follow a specific format, such as: 
```turtle
<http://example.org/PersonShape> <http://www.w3.org/ns/shacl#property> _:bc_0_n3-0 .
<http://example.org/PersonShape> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/shacl#NodeShape> .
_:bc_0_n3-0 <http://www.w3.org/ns/shacl#path> <http://xmlns.com/foaf/0.1/forname> .
``` 
 or
```turtle
<http://example.org/PersonShape> <http://www.w3.org/ns/shacl#property> <http://example.org/shacl/Property0>;
a <http://www.w3.org/ns/shacl#NodeShape>.
<http://example.org/shacl/Property0> <http://www.w3.org/ns/shacl#path> <http://xmlns.com/foaf/0.1/forname>.
```
Result without data-values-subject:
![image](https://github.com/user-attachments/assets/9d04694a-5dd1-461b-a5f4-e47c827c8f7a)

Result with data-values-subject:
![image](https://github.com/user-attachments/assets/15107a93-b4b0-47b9-ab68-88f2f3bd867b)

However, it works, when using a format, such as:
```turtle
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix ex: <http://example.org/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

ex:PersonShape a sh:NodeShape ;
  sh:targetClass foaf:Person ;

  sh:property [
    sh:path foaf:forname ;
  ] .
```
Result without data-values-subject:
![image](https://github.com/user-attachments/assets/f5ef80fe-17af-4dcd-a9e3-0891cc27bd65)

Result with data-values-subject:
![image](https://github.com/user-attachments/assets/b1627011-ad1e-44d6-a9bd-4da3e1e3efbc)

shacl-form element of the above:
```js
<shacl-form 
      data-values-subject="http://example.org/Natanael"
      data-shapes='@prefix foaf: <http://xmlns.com/foaf/0.1/> .
      @prefix ex: <http://example.org/> .
      @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
      @prefix sh: <http://www.w3.org/ns/shacl#> .
      @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
      
      ex:PersonShape a sh:NodeShape ;
        sh:targetClass foaf:Person ;
        
        sh:property [
          sh:path foaf:forname ;
        ] .
    '      
    data-values="
    <http://example.org/Natanael> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://xmlns.com/foaf/0.1/Person> <http://example.org/> .
    <http://example.org/Natanael> <http://xmlns.com/foaf/0.1/forname> 'Natanael' <http://example.org/> .
    "
></shacl-form>
```

Is it possible to fix this error, without changing the data-shapes format?

**Comment by s-tittel** [comment]
Hi and thanks for the feedback. When binding a data graph to the form, `<shacl-form>` only has some basic logic to determine the shacl shape to use for the values, one of which is using `sh:targetClass`. In your case, the triple
```
<http://example.org/Natanael> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://xmlns.com/foaf/0.1/Person>
```
results in using `ex:PersonShape`, because of its corresponding `sh:targetClass` definition. When this triple is missing (I guess this is the case in your first example), `shacl-form` doesn't know what shacl shape the data conforms to.

BTW, you can always manually set the shacl shape on the HTML element like so:
```
<shacl-form data-shape-subject="http://example.org/PersonShape" ...></shacl-form>
```

**Comment by dmap1514** [comment]
Thank you very much, that helped!
