### ISSUE TITLE
Green checkmark even when invalid?

### ISSUE THREAD

**Issue by benjaminaaron** [ULB-Darmstadt/shacl-form#5]
I was wondering why the green checkmark shows up on the left side of a field, even so the input is invalid? 
In this example, I am only getting the invalid-message upon clicking Submit. The green checkmark makes me think, the value is alright. A red cross or turning the whole field red would make more sense to me? 

![Screenshot 2023-12-23 at 21 56 46](https://github.com/ULB-Darmstadt/shacl-form/assets/5141792/b0e95a0f-5955-4d33-baa3-d09c37b2adb3)

And it seems the invalid-info is already present before clicking submit, because when hovering over  the little arrows, it does already show this message:

![Screenshot 2023-12-23 at 21 58 50](https://github.com/ULB-Darmstadt/shacl-form/assets/5141792/397cef79-417e-4c05-b879-528e0e1a2629)

**Comment by benjaminaaron** [comment]
In your *Basic usage* example I console-logged `event.detail?.valid` and it is actually `true` for invalid values. That doesn't seem right 🤔

**Comment by s-tittel** [comment]
Thanks for reporting. There are two separate validators at work here:
1. The browser validating the input field according the the HTML element attribute `type=number`. The messages in your screenshot are the result of that.
2. The [rdf validator library](https://github.com/zazuko/rdf-validate-shacl) that I use to validate the actual RDF data graph against the SHACL shape definitions, and this is where the green checkmark comes from.

There was a bug in my node shape definitions, which is now fixed. According to [the spec](https://www.w3.org/TR/shacl/#implicit-targetClass), my node shape was missing this triple:

`example:ArchitectureModelDataset  a rdfs:Class .`

RDF validation should now be working as expected.

**Comment by benjaminaaron** [comment]
It does work now as expected indeed, thanks!

Now I can't trigger the browser validation warning popup (from the screenshot) anymore though. I was hoping that would come up when I press Submit with warnings (which are now shown 👍) present. But instead the Submit-click takes me to the wrong field. Which also makes sense as a behaviour.

**Comment by s-tittel** [comment]
@benjaminaaron , please check version 1.3.5, I have reversed the validation order, so that browser validation executes before rdf graph validation.
