### ISSUE TITLE
Allow graph-modification before generating output?

### ISSUE THREAD

**Issue by benjaminaaron** [ULB-Darmstadt/shacl-form#7]
For my use case, it would be great if I'd get a chance to modify (e.g. add triples not generated via the form) [this graph](https://github.com/ULB-Darmstadt/shacl-form/blob/b010adb2c861b5ac3bb3fb1c960a24f8731a45f6/src/form.ts#L110-L115) before it gets serialized. Then I wouldn't have to import the serialized triples back into a temporary triple store to do this via another library. Any chance this might be possible?

**Comment by s-tittel** [comment]
This is now supported, the [serialize function](https://github.com/ULB-Darmstadt/shacl-form/tree/v1.3.4#element-functions) now accepts an optional graph parameter.

**Comment by benjaminaaron** [comment]
Oh great, thanks a lot for implementing this so fast!
